version: '3.8'
services:
  db:
    build: ./Backend
    image: 715841327332.dkr.ecr.us-east-1.amazonaws.com/wp-backend:8.0 #local/mysql-wp:8.0
    container_name: wp-db
    env_file: .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${DB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  wordpress:
    build: ./Frontend
    image: 715841327332.dkr.ecr.us-east-1.amazonaws.com/wp-frontend:latest #local/wordpress-custom:latest
    container_name: wp-app
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
    ports:
      - "8080:80"
    # For local persistence of new uploads (optional):
    # volumes:
    #   - ./Frontend/yuvi:/var/www/html/

volumes:
  db_data:
